version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: always 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - my_network

  influxdb:
    image: influxdb:1.8
    restart: always 
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=iot_machine_data
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - my_network

  data_generator:
    build:
      context: .
      dockerfile: Dockerfile.data_generator
    depends_on:
      - mqtt
      - influxdb
    env_file:
      - .env
    networks:
      - my_network

  mqtttoinfluxdb:
    build:
      context: .
      dockerfile: Dockerfile.mqtttoinfluxdb
    depends_on:
      - mqtt
      - influxdb
      - data_generator
    env_file:
      - .env
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    env_file:
      - .env
    networks:
      - my_network

  frontend:
    build:
      context: ./my-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
