apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-to-influxdb
spec:
  selector:
    matchLabels:
      app: mqtt-to-influxdb
  template:
    metadata:
      labels:
        app: mqtt-to-influxdb
    spec:
      containers:
      - name: mqtt-to-influxdb
        image: piyushbonde/iot_dashboard_project:mqtttoinfluxdb
        env:
        - name: INFLUXDB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: INFLUXDB_NAME
        - name: MQTT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MQTT_USERNAME
        - name: MQTT_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MQTT_BROKER
        - name: INFLUXDB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: INFLUXDB_HOST
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MQTT_PASSWORD
